version: '3'
services:
  sam_ruby_template:
    cap_add:
      - NET_ADMIN # for docker running
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash -c "sh run.sh && /bin/bash"
    volumes:
      - .:/app
